name: Deploy Application

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # Specify the branch to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up kubectl
      uses: actions/setup-kubectl@v2  # Set up kubectl to interact with Kubernetes
      with:
        kubectl-version: 'latest'  # Ensure you have the latest kubectl version

    - name: Set Kubeconfig for Local Kubernetes
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config  # Load the kubeconfig from GitHub Secrets

    - name: Login to ArgoCD
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
      env:
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}

    - name: Sync ArgoCD App
      run: |
        argocd app sync nginx-app --force  # Force sync the app with the latest changes
        argocd app wait nginx-app --sync   # Wait until the sync is complete
      env:
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
